const URL='https://bppqbhfsvwokfdawauht.supabase.co',KEY='sb_publishable_dGv-k8m6A9tACGpQsxaapg_IxrW5LfA';let token=localStorage.getItem('lu_token')||'',DB={equipes:[],setores:[],veiculos:[],registros:[]};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function req(path,opt={}){let h={'apikey':KEY,'Content-Type':'application/json'};if(token)h.Authorization='Bearer '+token;let r=await fetch(URL+path,{...opt,headers:{...h,...(opt.headers||{})}}),t=await r.text(),d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.msg||d?.message||d?.error_description||t||'Erro '+r.status);return d}
async function load(){[DB.equipes,DB.setores,DB.veiculos,DB.registros]=await Promise.all(['equipes','setores','veiculos','registros'].map(t=>req('/rest/v1/'+t+'?select=*&order=created_at.asc')));render()}
function eq(id){return DB.equipes.find(x=>x.id===id)}function st(id){return DB.setores.find(x=>x.id===id)}function fmt(n){return Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('side').classList.remove('open')}
window.go=go;document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('hamb').onclick=()=>$('side').classList.toggle('open');
function render(){let totalV=DB.registros.reduce((a,r)=>a+Number(r.viagens),0),totalM=DB.registros.reduce((a,r)=>a+Number(r.volume),0);$('dashcards').innerHTML=[['Viagens hoje',totalV,'green'],['Volume removido',fmt(totalM)+' m³','blue'],['Equipes em operação',DB.equipes.filter(e=>e.ativo).length,'purple'],['Setores atendidos',DB.setores.filter(s=>s.ativo).length,'orange']].map(x=>`<div class="card"><div class="label ${x[2]}">${x[0]}</div><div class="num ${x[2]}">${x[1]}</div><div class="sub">Dados registrados no sistema</div></div>`).join('');
let vals=DB.equipes.map(e=>DB.registros.filter(r=>r.equipe_id===e.id).reduce((a,r)=>a+Number(r.viagens),0)),mx=Math.max(1,...vals);$('bars').innerHTML=DB.equipes.map((e,i)=>`<div class="barwrap"><div class="bar" style="height:${Math.max(3,vals[i]/mx*145)}px"><b>${vals[i]}</b></div><span>${esc(e.nome)}</span></div>`).join('');
let days={};DB.registros.forEach(r=>days[r.data]=(days[r.data]||0)+Number(r.volume));let arr=Object.entries(days).sort(),max=Math.max(1,...arr.map(x=>x[1]));let pts=arr.length?arr.map((x,i)=>`${i/(Math.max(1,arr.length-1))*500},${165-x[1]/max*135}`).join(' '):'0,165 500,165';$('volumeLine').setAttribute('points',pts);$('volumeArea').setAttribute('points','0,180 '+pts+' 500,180');
$('prodTable').innerHTML=DB.equipes.map(e=>{let rr=DB.registros.filter(r=>r.equipe_id===e.id),v=rr.reduce((a,r)=>a+Number(r.viagens),0),m=rr.reduce((a,r)=>a+Number(r.volume),0),ss=new Set(rr.map(r=>r.setor_id)).size;return `<tr><td>${esc(e.nome)}</td><td>${v}</td><td>${fmt(m)}</td><td>${ss}</td><td>${rr.length?fmt(m/Math.max(1,new Set(rr.map(r=>r.data)).size)):0} m³</td></tr>`}).join('');
$('eqTable').innerHTML=DB.equipes.map(e=>`<tr><td><b>${esc(e.nome)}</b></td><td>${esc(e.responsavel||'Não informado')}</td><td>${e.pa}</td><td>${e.caminhoes}</td><td>${DB.setores.filter(s=>s.equipe_id===e.id).length}</td><td><span class="badge ok">${e.ativo?'Ativa':'Inativa'}</span></td></tr>`).join('');$('eqDetail').innerHTML=DB.equipes.map(e=>`<span class="chip"><b>${esc(e.nome)}</b> • 🚜 ${e.pa} • 🚛 ${e.caminhoes}</span>`).join('');
$('setTable').innerHTML=DB.setores.map(s=>`<tr><td>${esc(s.nome)}</td><td>${esc(eq(s.equipe_id)?.nome||'-')}</td><td><span class="badge ok">${s.ativo?'Ativo':'Inativo'}</span></td></tr>`).join('')||'<tr><td colspan="3">Nenhum setor cadastrado.</td></tr>';
$('veiTable').innerHTML=DB.veiculos.map(v=>`<tr><td>${esc(v.codigo)}</td><td>${esc(v.tipo)}</td><td>${fmt(v.capacidade)} m³</td><td>${esc(eq(v.equipe_id)?.nome||'-')}</td><td><span class="badge ok">${v.ativo?'Operando':'Inativo'}</span></td></tr>`).join('')||'<tr><td colspan="5">Nenhum veículo cadastrado.</td></tr>';
let opts='<option value="">Selecione...</option>'+DB.equipes.filter(e=>e.ativo).map(e=>`<option value="${e.id}">${esc(e.nome)}</option>`).join('');$('requipe').innerHTML=opts;$('fequipe').innerHTML='<option value="">Todas as equipes</option>'+opts.replace('<option value="">Selecione...</option>','');$('fsetor').innerHTML='<option value="">Todos os setores</option>'+DB.setores.map(s=>`<option value="${s.id}">${esc(s.nome)}</option>`).join('');
let rows=DB.registros.slice().sort((a,b)=>b.data.localeCompare(a.data)).map(r=>`<tr><td>${r.data}</td><td>${esc(eq(r.equipe_id)?.nome||'-')}</td><td>${esc(st(r.setor_id)?.nome||'-')}</td><td>${r.viagens}</td><td>${fmt(r.volume)} m³</td><td>${esc(r.material||'-')}</td></tr>`).join('');$('allRegs').innerHTML=rows||'<tr><td colspan="6">Nenhum registro.</td></tr>';
$('productionCards').innerHTML=[['Viagens',totalV],['Volume',fmt(totalM)+' m³'],['Registros',DB.registros.length],['Setores',new Set(DB.registros.map(r=>r.setor_id)).size]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="num green">${x[1]}</div></div>`).join('');
$('maintenance').innerHTML=DB.veiculos.length?DB.veiculos.map(v=>`<div class="alert"><b>${esc(v.codigo)}</b> — ${esc(v.tipo)} — ${v.ativo?'🟢 Operando':'🔴 Inativo'}</div>`).join(''):'Nenhum veículo cadastrado.';filterReport()}
$('requipe').onchange=()=>{let e=eq($('requipe').value);$('rpa').textContent=e?.pa||0;$('rcam').textContent=e?.caminhoes||0;$('rsetor').innerHTML='<option value="">Selecione o setor</option>'+DB.setores.filter(s=>s.equipe_id===$('requipe').value&&s.ativo).map(s=>`<option value="${s.id}">${esc(s.nome)}</option>`).join('')};function calc(){$('rvolume').value=(Number($('rviagens').value||0)*Number($('rcap').value||0)).toFixed(2)}$('rviagens').oninput=calc;$('rcap').oninput=calc;
$('regForm').onsubmit=async e=>{e.preventDefault();$('regmsg').textContent='Salvando...';try{await req('/rest/v1/registros',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({data:$('rdata').value,equipe_id:$('requipe').value,setor_id:$('rsetor').value,viagens:+$('rviagens').value,capacidade:+$('rcap').value,material:$('rmaterial').value,observacoes:$('robs').value})});$('regmsg').className='msg oktxt full';$('regmsg').textContent='Registro salvo com sucesso.';await load()}catch(x){$('regmsg').className='msg err full';$('regmsg').textContent=x.message}};
async function quickAdd(type){if(type==='equipe'){let nome=prompt('Nome da equipe:');if(!nome)return;let resp=prompt('Responsável:')||'',pa=+(prompt('Quantidade de pás carregadeiras:','0')||0),cam=+(prompt('Quantidade de caminhões:','0')||0);await req('/rest/v1/equipes',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({nome,responsavel:resp,pa,caminhoes:cam,ativo:true})})}if(type==='setor'){let nome=prompt('Nome do setor:');if(!nome)return;let nomes=DB.equipes.map((e,i)=>`${i+1} - ${e.nome}`).join('\n'),n=+(prompt('Escolha a equipe:\n'+nomes)||0),e=DB.equipes[n-1];if(!e)return;await req('/rest/v1/setores',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({nome,equipe_id:e.id,ativo:true})})}if(type==='veiculo'){let codigo=prompt('Código do veículo:');if(!codigo)return;let tipo=prompt('Tipo:','Basculante')||'Basculante',cap=+(prompt('Capacidade em m³:','18')||0),n=+(prompt('Equipe (1 a '+DB.equipes.length+'):')||0),e=DB.equipes[n-1];if(!e)return;await req('/rest/v1/veiculos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({codigo,tipo,capacidade:cap,equipe_id:e.id,ativo:true})})}await load()}
$('addEquipe').onclick=()=>quickAdd('equipe');$('addSetor').onclick=()=>quickAdd('setor');$('addVeiculo').onclick=()=>quickAdd('veiculo');
function filterReport(){let rs=DB.registros.filter(r=>(!$('fini').value||r.data>=$('fini').value)&&(!$('ffim').value||r.data<=$('ffim').value)&&(!$('fequipe').value||r.equipe_id===$('fequipe').value)&&(!$('fsetor').value||r.setor_id===$('fsetor').value));$('reportCards').innerHTML=[['Viagens Totais',rs.reduce((a,r)=>a+Number(r.viagens),0)],['Volume Total',fmt(rs.reduce((a,r)=>a+Number(r.volume),0))+' m³'],['Setores Atendidos',new Set(rs.map(r=>r.setor_id)).size],['Equipes Ativas',new Set(rs.map(r=>r.equipe_id)).size]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="num green">${x[1]}</div></div>`).join('');$('reportTable').innerHTML=rs.map(r=>`<tr><td>${r.data}</td><td>${esc(eq(r.equipe_id)?.nome||'-')}</td><td>${esc(st(r.setor_id)?.nome||'-')}</td><td>${r.viagens}</td><td>${fmt(r.volume)}</td><td>${esc(r.material||'-')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum resultado.</td></tr>'} $('filterBtn').onclick=filterReport;
$('csvBtn').onclick=()=>{let rows=[['Data','Equipe','Setor','Viagens','Volume','Material'],...DB.registros.map(r=>[r.data,eq(r.equipe_id)?.nome||'',st(r.setor_id)?.nome||'',r.viagens,r.volume,r.material||''])],csv='\ufeff'+rows.map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='relatorio-limpeza-urbana.csv';a.click()};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('authmsg').textContent='Entrando...';try{let d=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});token=d.access_token;localStorage.setItem('lu_token',token);$('login').classList.add('hidden');$('system').classList.remove('hidden');await load()}catch(x){$('authmsg').className='msg err';$('authmsg').textContent=x.message}};
$('signup').onclick=async()=>{let email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6){$('authmsg').className='msg err';$('authmsg').textContent='Informe e-mail e senha de pelo menos 6 caracteres.';return}try{let d=await req('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});$('authmsg').className='msg oktxt';$('authmsg').textContent=d.access_token?'Conta criada. Entrando...':'Conta criada. Confirme seu e-mail.';if(d.access_token){token=d.access_token;localStorage.setItem('lu_token',token);$('login').classList.add('hidden');$('system').classList.remove('hidden');await load()}}catch(x){$('authmsg').className='msg err';$('authmsg').textContent=x.message}};
$('logout').onclick=()=>{localStorage.removeItem('lu_token');token='';location.reload()};$('today').textContent=new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'});$('rdata').value=new Date().toISOString().slice(0,10);calc();if(token){$('login').classList.add('hidden');$('system').classList.remove('hidden');load().catch(()=>{localStorage.removeItem('lu_token');location.reload()})}