(()=>{
  const cfgKey='lu_config_v1';
  const defaults={nomeSistema:'Limpeza Urbana',orgao:'',capacidadePadrao:13,periodos:'Matutino, Vespertino, Integral',tituloRelatorio:'Relatório de Limpeza Urbana'};
  const getCfg=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(cfgKey)||'{}')}}catch{return {...defaults}}};
  const saveCfg=c=>localStorage.setItem(cfgKey,JSON.stringify(c));
  function ensureStyle(){if(document.getElementById('cfg-style'))return;const s=document.createElement('style');s.id='cfg-style';s.textContent=`
  .cfg-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.cfg-card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:18px;cursor:pointer;transition:.15s;min-height:150px}.cfg-card:hover{transform:translateY(-2px);box-shadow:0 7px 20px #102a4312}.cfg-card .ico{font-size:26px}.cfg-card h3{margin:10px 0 6px;font-size:15px}.cfg-card p{margin:0;color:var(--muted);font-size:11px;line-height:1.45}.cfg-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cfg-box{border:1px solid var(--line);border-radius:9px;padding:13px;background:#fafcfd}.cfg-box b{display:block;margin-bottom:4px}.cfg-back{margin-bottom:12px}.cfg-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cfg-form label{font-size:12px;font-weight:700}.cfg-form input,.cfg-form select{width:100%;margin-top:5px;padding:10px;border:1px solid #cfd9e2;border-radius:7px;background:#fff}.cfg-full{grid-column:1/-1}@media(max-width:850px){.cfg-grid{grid-template-columns:1fr 1fr}.cfg-form,.cfg-meta{grid-template-columns:1fr}.cfg-full{grid-column:auto}}@media(max-width:520px){.cfg-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function home(){ensureStyle();const sec=document.getElementById('config');if(!sec)return;sec.innerHTML=`<div class="toolbar"><div><h2>Configurações</h2><p>Central administrativa do sistema</p></div></div><div class="cfg-grid">
  <div class="cfg-card" onclick="cfgOpen('geral')"><div class="ico">⚙️</div><h3>Configurações Gerais</h3><p>Nome do sistema, órgão responsável e preferências básicas.</p></div>
  <div class="cfg-card" onclick="cfgOpen('usuarios')"><div class="ico">👥</div><h3>Usuários e Permissões</h3><p>Gerencie administradores, membros e status de acesso.</p></div>
  <div class="cfg-card" onclick="cfgOpen('operacao')"><div class="ico">🚛</div><h3>Parâmetros Operacionais</h3><p>Capacidade padrão, períodos e regras usadas nos registros.</p></div>
  <div class="cfg-card" onclick="cfgOpen('relatorios')"><div class="ico">📊</div><h3>Relatórios</h3><p>Título e informações administrativas usadas nas exportações.</p></div>
  <div class="cfg-card" onclick="cfgOpen('seguranca')"><div class="ico">🛡️</div><h3>Segurança</h3><p>Sessão atual, autenticação e ações de acesso.</p></div>
  <div class="cfg-card" onclick="cfgOpen('sobre')"><div class="ico">ℹ️</div><h3>Sobre o Sistema</h3><p>Versão, infraestrutura e informações técnicas.</p></div>
  </div>`}
  function panel(title,body){const sec=document.getElementById('config');sec.innerHTML=`<button class="btn secondary cfg-back" onclick="cfgHome()">← Voltar</button><div class="toolbar"><div><h2>${title}</h2><p>Configurações › ${title}</p></div></div><div class="panel">${body}</div>`}
  window.cfgHome=home;
  window.cfgOpen=function(id){const c=getCfg();if(id==='usuarios'){go('usuarios');return}if(id==='geral'){panel('Configurações Gerais',`<form id="cfgGeneral" class="cfg-form"><label>Nome do sistema<input name="nomeSistema" value="${esc(c.nomeSistema)}"></label><label>Órgão / Secretaria<input name="orgao" placeholder="Ex.: SEINFRA" value="${esc(c.orgao)}"></label><div class="cfg-full actions"><button class="btn primary">Salvar alterações</button></div><div id="cfgmsg" class="msg cfg-full"></div></form>`);document.getElementById('cfgGeneral').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),n={...c,nomeSistema:f.get('nomeSistema').trim()||defaults.nomeSistema,orgao:f.get('orgao').trim()};saveCfg(n);document.getElementById('cfgmsg').className='msg oktxt cfg-full';document.getElementById('cfgmsg').textContent='Configurações salvas.'};return}
  if(id==='operacao'){panel('Parâmetros Operacionais',`<form id="cfgOp" class="cfg-form"><label>Capacidade padrão por viagem (m³)<input name="capacidade" type="number" step="0.1" min="0" value="${c.capacidadePadrao}"></label><label>Períodos disponíveis<input name="periodos" value="${esc(c.periodos)}"></label><div class="cfg-full hint">A capacidade padrão será usada para preencher novos registros. Os períodos podem ser separados por vírgula.</div><div class="cfg-full actions"><button class="btn primary">Salvar alterações</button></div><div id="cfgopmsg" class="msg cfg-full"></div></form>`);document.getElementById('cfgOp').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),n={...c,capacidadePadrao:+f.get('capacidade')||13,periodos:f.get('periodos').trim()||defaults.periodos};saveCfg(n);const cap=document.getElementById('rcap');if(cap)cap.value=n.capacidadePadrao;document.getElementById('cfgopmsg').className='msg oktxt cfg-full';document.getElementById('cfgopmsg').textContent='Parâmetros atualizados.'};return}
  if(id==='relatorios'){panel('Relatórios',`<form id="cfgRel" class="cfg-form"><label class="cfg-full">Título padrão dos relatórios<input name="titulo" value="${esc(c.tituloRelatorio)}"></label><label class="cfg-full">Órgão responsável<input value="${esc(c.orgao||'Não informado')}" disabled></label><div class="cfg-full hint">Essas informações ficam preparadas para uso em futuras exportações PDF e cabeçalhos oficiais.</div><div class="cfg-full actions"><button class="btn primary">Salvar alterações</button></div><div id="cfgrelmsg" class="msg cfg-full"></div></form>`);document.getElementById('cfgRel').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);saveCfg({...c,tituloRelatorio:f.get('titulo').trim()||defaults.tituloRelatorio});document.getElementById('cfgrelmsg').className='msg oktxt cfg-full';document.getElementById('cfgrelmsg').textContent='Preferências de relatório salvas.'};return}
  if(id==='seguranca'){panel('Segurança',`<div class="cfg-meta"><div class="cfg-box"><b>Autenticação</b>Supabase Auth</div><div class="cfg-box"><b>Proteção de dados</b>Row Level Security (RLS)</div><div class="cfg-box"><b>Sessão</b>Usuário autenticado</div><div class="cfg-box"><b>Ação</b><button class="btn danger" onclick="document.getElementById('logout').click()">Encerrar sessão</button></div></div>`);return}
  if(id==='sobre'){panel('Sobre o Sistema',`<div class="cfg-meta"><div class="cfg-box"><b>Sistema</b>Limpeza Urbana</div><div class="cfg-box"><b>Versão</b>3.0</div><div class="cfg-box"><b>Banco de dados</b>Supabase PostgreSQL</div><div class="cfg-box"><b>Hospedagem</b>Vercel</div><div class="cfg-box"><b>Autenticação</b>Supabase Auth</div><div class="cfg-box"><b>Segurança</b>RLS habilitado</div></div>`);return}}
  const oldGo=window.go;window.go=function(id){oldGo(id);if(id==='config')setTimeout(home,0)};
  window.addEventListener('DOMContentLoaded',()=>{ensureStyle();setTimeout(()=>{const cap=document.getElementById('rcap');if(cap)cap.value=getCfg().capacidadePadrao;home()},250)});
})();